# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    # The branches below must be a subset of the branches above
    branches: [develop]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        if: github.event.pull_request.assignee != null && github.event.pull_request.draft == false
        run: yarn
        # ðŸ‘‡ Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        if: github.event.pull_request.assignee != null && github.event.pull_request.draft == false && github.ref != 'refs/heads/develop'
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
       - name: Publish to Chromatic
        if: github.event.pull_request.assignee != null && github.event.pull_request.draft == false && github.ref == 'refs/heads/develop'
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true 
